SET NOCOUNT ON;
IF DB_NAME() <> N'jemnexusb_prod' THROW 51000, 'PRODUCTION_DATABASE_IDENTITY_MISMATCH', 1;
IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE database_id=DB_ID() AND snapshot_isolation_state_desc=N'ON')
    THROW 51000, 'NO_GO_SNAPSHOT_ISOLATION_NOT_ENABLED', 1;
SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
BEGIN TRY
    BEGIN TRANSACTION;
    EXEC sys.sp_executesql N'IF EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON s.schema_id=t.schema_id WHERE t.name IN (N''__EFMigrationsHistory'',N''AppUsers'',N''AppUserPermissions'',N''Brands'',N''Categories'',N''Suppliers'',N''TechnicalSheets'',N''Products'',N''ProductImages'',N''ProductSpecs'',N''Promotions'',N''HomeSectionItems'',N''QuoteRequests'',N''CustomerProfiles'',N''CommercialQuotes'',N''CommercialQuoteItems'',N''CommercialQuoteFolioCounters'',N''CommercialQuoteIssueIdempotencyRecords'',N''AppRefreshTokens'') AND s.name<>N''jemnexusb_api'') THROW 51000,''SCHEMA_MISMATCH'',1;
SELECT N''JemNexusProductionSchemaBaseline'' reportType,DB_NAME() [database],N''jemnexusb_api'' [schema],N''jemnexusb_api'' historySchema,N''jemnexusb_api'' sequenceSchema,N''database'' markerScope,SYSUTCDATETIME() evidenceCapturedUtc,(SELECT COUNT_BIG(*) FROM [jemnexusb_api].[__EFMigrationsHistory]) migrationCount;
SELECT MigrationId FROM [jemnexusb_api].[__EFMigrationsHistory] ORDER BY MigrationId;
SELECT t.name TableName,c.column_id Ordinal,c.name ColumnName,ty.name TypeName,c.max_length MaxLength,c.precision Precision,c.scale Scale,c.is_nullable Nullable,c.collation_name Collation FROM sys.tables t JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.columns c ON c.object_id=t.object_id JOIN sys.types ty ON ty.user_type_id=c.user_type_id WHERE s.name=N''jemnexusb_api'' AND t.name IN (N''AppUsers'',N''AppUserPermissions'',N''Brands'',N''Categories'',N''Suppliers'',N''TechnicalSheets'',N''Products'',N''ProductImages'',N''ProductSpecs'',N''Promotions'',N''HomeSectionItems'',N''QuoteRequests'',N''CustomerProfiles'',N''CommercialQuotes'',N''CommercialQuoteItems'',N''CommercialQuoteFolioCounters'',N''CommercialQuoteIssueIdempotencyRecords'') ORDER BY t.name,c.column_id;
SELECT t.name TableName,k.name KeyName,ic.key_ordinal Ordinal,c.name ColumnName FROM sys.key_constraints k JOIN sys.tables t ON t.object_id=k.parent_object_id JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.index_columns ic ON ic.object_id=t.object_id AND ic.index_id=k.unique_index_id JOIN sys.columns c ON c.object_id=t.object_id AND c.column_id=ic.column_id WHERE s.name=N''jemnexusb_api'' AND k.type=''PK'' AND t.name IN (N''AppUsers'',N''AppUserPermissions'',N''Brands'',N''Categories'',N''Suppliers'',N''TechnicalSheets'',N''Products'',N''ProductImages'',N''ProductSpecs'',N''Promotions'',N''HomeSectionItems'',N''QuoteRequests'',N''CustomerProfiles'',N''CommercialQuotes'',N''CommercialQuoteItems'',N''CommercialQuoteFolioCounters'',N''CommercialQuoteIssueIdempotencyRecords'') ORDER BY t.name,ic.key_ordinal;
SELECT ps.name ParentSchema,pt.name TableName,fk.name ForeignKey,pc.name ColumnName,rs.name ReferencedSchema,rt.name ReferencedTable,rc.name ReferencedColumn,fk.delete_referential_action_desc DeleteAction,fk.is_disabled IsDisabled,fk.is_not_trusted IsNotTrusted FROM sys.foreign_keys fk JOIN sys.tables pt ON pt.object_id=fk.parent_object_id JOIN sys.schemas ps ON ps.schema_id=pt.schema_id JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id=fk.object_id JOIN sys.columns pc ON pc.object_id=fkc.parent_object_id AND pc.column_id=fkc.parent_column_id JOIN sys.tables rt ON rt.object_id=fk.referenced_object_id JOIN sys.schemas rs ON rs.schema_id=rt.schema_id JOIN sys.columns rc ON rc.object_id=fkc.referenced_object_id AND rc.column_id=fkc.referenced_column_id WHERE ps.name=N''jemnexusb_api'' AND pt.name IN (N''AppUsers'',N''AppUserPermissions'',N''Brands'',N''Categories'',N''Suppliers'',N''TechnicalSheets'',N''Products'',N''ProductImages'',N''ProductSpecs'',N''Promotions'',N''HomeSectionItems'',N''QuoteRequests'',N''CustomerProfiles'',N''CommercialQuotes'',N''CommercialQuoteItems'',N''CommercialQuoteFolioCounters'',N''CommercialQuoteIssueIdempotencyRecords'') ORDER BY pt.name,fk.name,fkc.constraint_column_id;
SELECT t.name TableName,i.name IndexName,i.is_unique IsUnique,i.filter_definition FilterDefinition,ic.key_ordinal Ordinal,c.name ColumnName FROM sys.indexes i JOIN sys.tables t ON t.object_id=i.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE s.name=N''jemnexusb_api'' AND i.is_hypothetical=0 AND i.name IS NOT NULL AND t.name IN (N''AppUsers'',N''AppUserPermissions'',N''Brands'',N''Categories'',N''Suppliers'',N''TechnicalSheets'',N''Products'',N''ProductImages'',N''ProductSpecs'',N''Promotions'',N''HomeSectionItems'',N''QuoteRequests'',N''CustomerProfiles'',N''CommercialQuotes'',N''CommercialQuoteItems'',N''CommercialQuoteFolioCounters'',N''CommercialQuoteIssueIdempotencyRecords'') ORDER BY t.name,i.name,ic.key_ordinal,ic.index_column_id;
SELECT t.name TableName,cc.name CheckName,cc.definition Definition,cc.is_disabled IsDisabled,cc.is_not_trusted IsNotTrusted FROM sys.check_constraints cc JOIN sys.tables t ON t.object_id=cc.parent_object_id JOIN sys.schemas s ON s.schema_id=t.schema_id WHERE s.name=N''jemnexusb_api'' AND t.name IN (N''AppUsers'',N''AppUserPermissions'',N''Brands'',N''Categories'',N''Suppliers'',N''TechnicalSheets'',N''Products'',N''ProductImages'',N''ProductSpecs'',N''Promotions'',N''HomeSectionItems'',N''QuoteRequests'',N''CustomerProfiles'',N''CommercialQuotes'',N''CommercialQuoteItems'',N''CommercialQuoteFolioCounters'',N''CommercialQuoteIssueIdempotencyRecords'') ORDER BY t.name,cc.name;
SELECT t.name TableName,ic.name ColumnName,CONVERT(nvarchar(40),ic.seed_value) SeedValue,CONVERT(nvarchar(40),ic.increment_value) IncrementValue FROM sys.identity_columns ic JOIN sys.tables t ON t.object_id=ic.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id WHERE s.name=N''jemnexusb_api'' AND t.name IN (N''AppUsers'',N''AppUserPermissions'',N''Brands'',N''Categories'',N''Suppliers'',N''TechnicalSheets'',N''Products'',N''ProductImages'',N''ProductSpecs'',N''Promotions'',N''HomeSectionItems'',N''QuoteRequests'',N''CustomerProfiles'',N''CommercialQuotes'',N''CommercialQuoteItems'',N''CommercialQuoteFolioCounters'',N''CommercialQuoteIssueIdempotencyRecords'') ORDER BY t.name,ic.name;
SELECT s.name SchemaName,q.name SequenceName,CONVERT(nvarchar(40),q.start_value) StartValue,CONVERT(nvarchar(40),q.increment) IncrementValue FROM sys.sequences q JOIN sys.schemas s ON s.schema_id=q.schema_id WHERE s.name=N''jemnexusb_api'' AND q.name=N''SellerCodeSequence'';';
    ROLLBACK TRANSACTION;
    IF @@TRANCOUNT <> 0 THROW 51000, 'BASELINE_TRANSACTION_NOT_CLOSED', 1;
    SELECT N'BASELINE_CAPTURE_COMPLETE' CaptureStatus;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 OR @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
