# Generated by Django 5.2.1 on 2026-04-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_quote_request_management_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("machinery_promotions", "Promociones en maquinarias"),
                            ("spare_parts_offers", "Oferta en repuestos"),
                            ("repair_services", "Servicios de reparación"),
                        ],
                        max_length=40,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_section_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "position", "id"],
                "unique_together": {("section", "position"), ("section", "product")},
            },
        ),
    ]
