import { useState } from 'react'
import type { ProductListItem } from '../../types/catalog'
import type { QuoteCurrency, QuoteEditorItem } from '../../types/commercialQuote'
import { emptyQuoteItem, finalUnitNet, isEmptyItem, money } from '../../utils/commercialQuote'
import { ProductSearchModal } from './ProductSearchModal'

export function QuoteItemsEditor({ currency, items, disabled, onChange }: { currency: QuoteCurrency; items: QuoteEditorItem[]; disabled: boolean; onChange: (items: QuoteEditorItem[]) => void }) {
  const [active, setActive] = useState<number | null>(null)
  const update = (index: number, patch: Partial<QuoteEditorItem>) => { const next = items.map((item, i) => i === index ? { ...item, ...patch } : item); const last = next[next.length - 1]; if (last && !isEmptyItem(last) && last.product_name && last.quantity && last.unit_net_amount) next.push(emptyQuoteItem()); onChange(next) }
  const select = (product: ProductListItem) => { if (active === null) return; update(active, { source: 'Catalog', product_id: product.id, product_name: product.name, brand_name: product.brand?.name ?? '', model_name: product.model ?? '' }); setActive(null) }
  return <>{active !== null ? <ProductSearchModal onClose={() => setActive(null)} onSelect={select} onManual={() => { update(active, { source: 'FreeText', product_id: null, product_name: '', brand_name: '', model_name: '' }); setActive(null) }} /> : null}
    <div className="quote-items" role="table"><div className="quote-items__head" role="row"><span>Item</span><span>Producto</span><span>Marca y modelo</span><span>Cantidad</span><span>Moneda</span><span>Valor unitario neto</span><span>Descuento en %</span><span>Valor unitario final neto</span><span /></div>
    {items.map((item, index) => <div className="quote-item" role="row" key={item.key}><span data-label="Item">{index + 1}</span><div data-label="Producto">{item.source === 'FreeText' ? <input aria-label={`Producto ${index + 1}`} value={item.product_name} maxLength={220} disabled={disabled} onChange={e => update(index, { product_name: e.target.value })} /> : <button type="button" disabled={disabled} onClick={() => setActive(index)}>{item.product_name || 'Buscar producto'}</button>}</div>
      <div data-label="Marca y modelo">{item.source === 'FreeText' ? <><input aria-label={`Marca ${index + 1}`} placeholder="Marca" value={item.brand_name} maxLength={120} disabled={disabled} onChange={e => update(index, { brand_name: e.target.value })} /><input aria-label={`Modelo ${index + 1}`} placeholder="Modelo" value={item.model_name} maxLength={120} disabled={disabled} onChange={e => update(index, { model_name: e.target.value })} /></> : <span>{[item.brand_name, item.model_name].filter(Boolean).join(' · ') || '—'}</span>}</div>
      <input data-label="Cantidad" aria-label={`Cantidad ${index + 1}`} type="number" min="1" step="1" value={item.quantity} disabled={disabled} onChange={e => update(index, { quantity: e.target.value })} /><span data-label="Moneda">{currency}</span><input data-label="Valor unitario neto" aria-label={`Valor unitario neto ${index + 1}`} type="number" min="0.01" step="0.01" value={item.unit_net_amount} disabled={disabled} onChange={e => update(index, { unit_net_amount: e.target.value })} /><input data-label="Descuento en %" aria-label={`Descuento ${index + 1}`} type="number" min="0" max="100" step="0.01" value={item.discount_percent} disabled={disabled} onChange={e => update(index, { discount_percent: e.target.value })} /><output data-label="Valor unitario final neto">{money(finalUnitNet(item, currency), currency)}</output><button type="button" disabled={disabled} onClick={() => onChange(items.length === 1 ? [emptyQuoteItem()] : items.filter((_, i) => i !== index))}>Eliminar</button></div>)}</div>
    {currency === 'USD' ? <p className="usd-note">Los valores expresados en USD se facturarán utilizando el valor del dólar vigente al momento de emitir la factura.</p> : null}</>
}
