// <auto-generated />
using System;
using JemNexus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JemNexus.Api.Data.Migrations
{
    [DbContext(typeof(JemNexusDbContext))]
    partial class JemNexusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<long>("SellerCodeSequence")
                .StartsAt(1L)
                .IncrementsBy(1);

            modelBuilder.Entity("JemNexus.Api.Models.AppRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PasswordVersion")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("AppRefreshTokens", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsStaff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuperuser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SellerCode")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.HasIndex("SellerCode")
                        .IsUnique()
                        .HasFilter("[SellerCode] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppUsers_Role_SellerCode", "([Role] = 'seller' AND [SellerCode] IS NOT NULL) OR ([Role] <> 'seller' AND [SellerCode] IS NULL)");
                        });
                });

            modelBuilder.Entity("JemNexus.Api.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("machinery");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsActive");

                    b.HasIndex("Order");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProductType");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.CommercialQuote", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Folio").HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<int?>("FolioYear").HasColumnType("int");
                    b.Property<long?>("FolioSequenceNumber").HasColumnType("bigint");
                    b.Property<DateTime?>("IssuedAtUtc").HasColumnType("datetime2");
                    b.Property<DateOnly?>("IssuedOn").HasColumnType("date");
                    b.Property<DateTimeOffset>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("datetimeoffset").HasDefaultValueSql("SYSUTCDATETIME()");
                    b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("nvarchar(3)");
                    b.Property<int?>("CustomerProfileId").HasColumnType("int");
                    b.Property<string>("CustomerBusinessName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("CustomerRut").IsRequired().HasMaxLength(12).HasColumnType("nvarchar(12)");
                    b.Property<string>("CustomerBusinessActivity").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("CustomerAddress").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("CustomerPhone").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.Property<string>("CustomerCityOrCommune").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("CustomerContactName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("CustomerEmail").HasMaxLength(254).HasColumnType("nvarchar(254)");
                    b.Property<string>("DetailedDescription").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<decimal>("NetAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<int>("ResponsibleSellerId").HasColumnType("int");
                    b.Property<string>("ResponsibleSellerCode").IsRequired().HasMaxLength(24).HasColumnType("nvarchar(24)");
                    b.Property<string>("ResponsibleSellerName").IsRequired().HasMaxLength(180).HasColumnType("nvarchar(180)");
                    b.Property<string>("ResponsibleSellerEmail").HasMaxLength(254).HasColumnType("nvarchar(254)");
                    b.Property<string>("ResponsibleSellerPhone").HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<string>("SaleCondition").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Draft");
                    b.Property<decimal>("TaxAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<decimal>("TaxRatePercent").ValueGeneratedOnAdd().HasPrecision(5, 2).HasColumnType("decimal(5,2)").HasDefaultValue(19.00m);
                    b.Property<decimal>("TotalAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<DateTimeOffset>("UpdatedAt").ValueGeneratedOnAdd().HasColumnType("datetimeoffset").HasDefaultValueSql("SYSUTCDATETIME()");
                    b.Property<int>("ValidityDays").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(15);
                    b.HasKey("Id"); b.HasIndex("CreatedAt"); b.HasIndex("CustomerProfileId"); b.HasIndex("ResponsibleSellerId"); b.HasIndex("Status"); b.HasIndex("Folio").IsUnique().HasDatabaseName("UX_CommercialQuotes_Folio").HasFilter("[Folio] IS NOT NULL"); b.HasIndex("FolioYear", "FolioSequenceNumber").IsUnique().HasDatabaseName("UX_CommercialQuotes_FolioYear_Sequence").HasFilter("[FolioYear] IS NOT NULL AND [FolioSequenceNumber] IS NOT NULL"); b.ToTable("CommercialQuotes");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CommercialQuoteFolioCounter", b =>
                {
                    b.Property<int>("Year").ValueGeneratedNever().HasColumnType("int");
                    b.Property<long>("LastNumber").HasColumnType("bigint");
                    b.HasKey("Year");
                    b.ToTable("CommercialQuoteFolioCounters");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CommercialQuoteIssueIdempotencyRecord", b =>
                {
                    b.Property<int>("ResponsibleSellerId").HasColumnType("int");
                    b.Property<Guid>("IdempotencyKey").HasColumnType("uniqueidentifier");
                    b.Property<int>("CommercialQuoteId").HasColumnType("int");
                    b.Property<DateTimeOffset>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("datetimeoffset").HasDefaultValueSql("SYSUTCDATETIME()");
                    b.Property<string>("RequestFingerprint").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.HasKey("ResponsibleSellerId", "IdempotencyKey");
                    b.HasIndex("CommercialQuoteId").IsUnique().HasDatabaseName("UX_CommercialQuoteIssueIdempotencyRecords_CommercialQuoteId");
                    b.ToTable("CommercialQuoteIssueIdempotencyRecords");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CommercialQuoteItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int"); SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("BrandName").HasMaxLength(120).HasColumnType("nvarchar(120)"); b.Property<int>("CommercialQuoteId").HasColumnType("int"); b.Property<decimal>("DiscountPercent").HasPrecision(5, 2).HasColumnType("decimal(5,2)"); b.Property<decimal>("FinalUnitNetAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)"); b.Property<decimal>("LineNetAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)"); b.Property<string>("ModelName").HasMaxLength(120).HasColumnType("nvarchar(120)"); b.Property<string>("Origin").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)"); b.Property<int>("Position").HasColumnType("int"); b.Property<int?>("ProductId").HasColumnType("int"); b.Property<string>("ProductName").IsRequired().HasMaxLength(220).HasColumnType("nvarchar(220)"); b.Property<int>("Quantity").HasColumnType("int"); b.Property<decimal>("UnitNetAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.HasKey("Id"); b.HasIndex("ProductId"); b.HasIndex("CommercialQuoteId", "Position").IsUnique(); b.ToTable("CommercialQuoteItems");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CommercialQuoteIssueIdempotencyRecord", b =>
                {
                    b.HasOne("JemNexus.Api.Models.CommercialQuote", "CommercialQuote").WithOne().HasForeignKey("JemNexus.Api.Models.CommercialQuoteIssueIdempotencyRecord", "CommercialQuoteId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("JemNexus.Api.Models.AppUser", "ResponsibleSeller").WithMany().HasForeignKey("ResponsibleSellerId").OnDelete(DeleteBehavior.NoAction).IsRequired();
                    b.Navigation("CommercialQuote");
                    b.Navigation("ResponsibleSeller");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CustomerProfile", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Address").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("BusinessActivity").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("BusinessName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("CityOrCommune").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("ContactName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<DateTimeOffset>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("datetimeoffset").HasDefaultValueSql("SYSUTCDATETIME()");
                    b.Property<int?>("CreatedById").HasColumnType("int");
                    b.Property<string>("Email").HasMaxLength(254).HasColumnType("nvarchar(254)");
                    b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(true);
                    b.Property<string>("NormalizedBusinessName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("NormalizedRut").IsRequired().HasMaxLength(12).HasColumnType("nvarchar(12)");
                    b.Property<string>("Phone").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.Property<string>("Rut").IsRequired().HasMaxLength(12).HasColumnType("nvarchar(12)");
                    b.Property<DateTimeOffset>("UpdatedAt").ValueGeneratedOnAdd().HasColumnType("datetimeoffset").HasDefaultValueSql("SYSUTCDATETIME()");
                    b.Property<int?>("UpdatedById").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("CreatedById");
                    b.HasIndex("NormalizedBusinessName");
                    b.HasIndex("NormalizedRut").IsUnique();
                    b.HasIndex("UpdatedById");
                    b.ToTable("CustomerProfiles", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.HomeSectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Section", "Position")
                        .IsUnique();

                    b.HasIndex("Section", "ProductId")
                        .IsUnique();

                    b.ToTable("HomeSectionItems", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("not_applicable");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int?>("HoursMeter")
                        .HasColumnType("int");

                    b.Property<bool>("IncludesCommercialTechnicalAdvice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IncludesCoordinatedDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IncludesTechnicalReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal?>("MaximumLoadCapacityKg")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("MachineWeightKg")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("PowerSource")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("CLP");

                    b.Property<string>("PriceTaxMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("plus_vat");

                    b.Property<bool>("PriceVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("machinery");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)")
                        .HasDefaultValue("");

                    b.Property<string>("Sku")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TerrainType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("on_request");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicalSheetId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.Property<decimal?>("WorkingHeightM")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Condition");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ProductType");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasFilter("[Sku] IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StockStatus");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TechnicalSheetId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsMain");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ProductId", "Order", "Id");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.ProductSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ProductId", "Order", "Id");

                    b.ToTable("ProductSpecs", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasDefaultValue("");

                    b.Property<string>("ButtonUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)")
                        .HasDefaultValue("");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EndsAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Order");

                    b.HasIndex("ProductId");

                    b.HasIndex("StartsAt");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.QuoteRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("ContactedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasDefaultValue("");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("InternalNotes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredContactMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("QuotedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SellerResponse")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("new");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProductId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedById");

                    b.ToTable("QuoteRequests", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.TechnicalSheet", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ContentType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<DateTimeOffset>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("datetimeoffset").HasDefaultValueSql("SYSUTCDATETIME()");
                    b.Property<string>("Name").IsRequired().HasMaxLength(220).HasColumnType("nvarchar(220)");
                    b.Property<string>("OriginalFileName").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<long>("SizeBytes").HasColumnType("bigint");
                    b.Property<string>("StorageKey").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<DateTimeOffset>("UpdatedAt").ValueGeneratedOnAdd().HasColumnType("datetimeoffset").HasDefaultValueSql("SYSUTCDATETIME()");
                    b.HasKey("Id");
                    b.ToTable("TechnicalSheets", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("JemNexus.Api.Models.AppRefreshToken", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Brand", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Category", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Parent");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.HomeSectionItem", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.Product", "Product")
                        .WithMany("HomeSectionItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Product");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Product", b =>
                {
                    b.HasOne("JemNexus.Api.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.TechnicalSheet", "TechnicalSheet")
                        .WithMany("Products")
                        .HasForeignKey("TechnicalSheetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("Supplier");

                    b.Navigation("TechnicalSheet");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.ProductImage", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Product");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.ProductSpec", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.Product", "Product")
                        .WithMany("Specs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Product");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Promotion", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Product");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.QuoteRequest", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.Product", "Product")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Product");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CommercialQuote", b =>
                {
                    b.HasOne("JemNexus.Api.Models.CustomerProfile", "CustomerProfile").WithMany().HasForeignKey("CustomerProfileId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("JemNexus.Api.Models.AppUser", "ResponsibleSeller").WithMany().HasForeignKey("ResponsibleSellerId").OnDelete(DeleteBehavior.NoAction).IsRequired();
                    b.Navigation("CustomerProfile"); b.Navigation("ResponsibleSeller");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CommercialQuoteItem", b =>
                {
                    b.HasOne("JemNexus.Api.Models.CommercialQuote", "CommercialQuote").WithMany("Items").HasForeignKey("CommercialQuoteId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("JemNexus.Api.Models.Product", "Product").WithMany().HasForeignKey("ProductId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("CommercialQuote"); b.Navigation("Product");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CustomerProfile", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy").WithMany().HasForeignKey("CreatedById").OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy").WithMany().HasForeignKey("UpdatedById").OnDelete(DeleteBehavior.NoAction);
                    b.Navigation("CreatedBy");
                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Supplier", b =>
                {
                    b.HasOne("JemNexus.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JemNexus.Api.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JemNexus.Api.Models.TechnicalSheet", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JemNexus.Api.Models.CommercialQuote", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JemNexus.Api.Models.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Product", b =>
                {
                    b.Navigation("HomeSectionItems");

                    b.Navigation("Images");

                    b.Navigation("Promotions");

                    b.Navigation("QuoteRequests");

                    b.Navigation("Specs");
                });

            modelBuilder.Entity("JemNexus.Api.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
