import { useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { AdminIcon } from '../../components/admin/AdminIcon'
import { AdminLayout } from '../../components/admin/AdminLayout'
import { AdminPageHeader } from '../../components/admin/AdminPageHeader'
import { useAdminUser } from '../../components/admin/ProtectedRoute'
import { safeUserMutationError } from '../../components/admin/UserForm'
import { ApiError } from '../../services/api'
import { clearSession } from '../../services/authApi'
import { deactivateManagedUser, getUserPermissionCatalog, listManagedUsers, type ManagedRole, type ManagedUser } from '../../services/adminUsersApi'
import { useToast } from '../../toasts/ToastContext'
import { ADMIN_TOASTS } from '../../toasts/adminToastMessages'

type StatusFilter = 'all' | 'active' | 'inactive'; type RoleFilter = 'all' | ManagedRole
function formatDate(value: string | null) { if (!value) return 'Nunca'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Fecha no disponible' : new Intl.DateTimeFormat('es-CL', { dateStyle: 'medium', timeStyle: 'short' }).format(date) }
export function AdminUsersPage() {
  const navigate = useNavigate(); const toast = useToast(); const location = useLocation(); const session = useAdminUser()
  const [users, setUsers] = useState<ManagedUser[]>([]); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState<StatusFilter>('all'); const [role, setRole] = useState<RoleFilter>('all'); const [permissionTotal, setPermissionTotal] = useState(29)
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(false); const [target, setTarget] = useState<ManagedUser | null>(null); const [mutationError, setMutationError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const [reload, setReload] = useState(0); const [notice, setNotice] = useState<string | null>(() => (location.state as { notice?: string } | null)?.notice ?? null)
  const opener = useRef<HTMLElement | null>(null); const cancel = useRef<HTMLButtonElement>(null)
  useEffect(() => { const timer = window.setTimeout(() => setQuery(search.trim()), 350); return () => window.clearTimeout(timer) }, [search])
  useEffect(() => { const controller = new AbortController(); getUserPermissionCatalog(controller.signal).then((catalog) => setPermissionTotal(catalog.seller_grantable.length)).catch(() => undefined); return () => controller.abort() }, [])
  useEffect(() => { const controller = new AbortController(); setLoading(true); setLoadError(false); listManagedUsers({ search: query || undefined, is_active: status === 'all' ? undefined : status === 'active', role: role === 'all' ? undefined : role }, controller.signal).then(setUsers).catch((error) => { if (error instanceof DOMException && error.name === 'AbortError') return; if (error instanceof ApiError && error.status === 401) { clearSession(); navigate('/login', { replace: true }); return } setLoadError(true) }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [navigate, query, reload, role, status])
  useEffect(() => { if (!target) return; cancel.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape' && !submitting) close() }; document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key) }, [target, submitting])
  const close = () => { setTarget(null); setMutationError(null); window.setTimeout(() => opener.current?.focus(), 0) }
  const confirm = async () => { if (!target || submitting) return; setSubmitting(true); try { await deactivateManagedUser(target.id); toast.success(ADMIN_TOASTS.user.deactivate.success); close(); setReload((value) => value + 1) } catch (error) { toast.error(ADMIN_TOASTS.user.deactivate.error); setMutationError(safeUserMutationError(error)) } finally { setSubmitting(false) } }
  const criteria = Boolean(query) || status !== 'all' || role !== 'all'
  return <AdminLayout>
    <AdminPageHeader title="Usuarios" description="Administra cuentas, roles y permisos de acceso al panel." actions={<button className="btn btn--accent" onClick={() => navigate('/admin/usuarios/nuevo')}><AdminIcon name="plus" /> Crear usuario</button>} />
    <div className="admin-users-content">
      <div className="admin-users-toolbar" role="search"><div className="admin-users-toolbar__search"><label htmlFor="user-search">Buscar por usuario, código, correo o nombre</label><div className="admin-users-search"><input id="user-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por usuario, código, correo o nombre" />{search ? <button className="btn btn--secondary" onClick={() => setSearch('')}>Limpiar</button> : null}</div></div><div className="admin-users-toolbar__filter"><label htmlFor="user-status">Estado</label><select id="user-status" value={status} onChange={(event) => setStatus(event.target.value as StatusFilter)}><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></div><div className="admin-users-toolbar__filter admin-users-toolbar__filter--role"><label htmlFor="user-role">Rol</label><select id="user-role" value={role} onChange={(event) => setRole(event.target.value as RoleFilter)}><option value="all">Todos</option><option value="support_admin">Superadministradores</option><option value="seller">Vendedores</option></select></div></div>
      <div className="admin-users-announcer" aria-live="polite">{notice ? <p className="ui-note ui-note--success">{notice}</p> : null}{loading ? <p className="ui-note">Cargando usuarios…</p> : null}</div>
      {loadError ? <div className="admin-users-empty" role="alert"><p>No fue posible cargar los usuarios.</p><button className="btn btn--secondary" onClick={() => setReload((value) => value + 1)}>Reintentar</button></div> : null}
      {!loading && !loadError && !users.length ? <p className="admin-users-empty">{criteria ? 'No se encontraron usuarios con los criterios seleccionados.' : 'Todavía no existen usuarios administrables.'}</p> : null}
      {!loadError && users.length ? <div className="admin-users-list">{users.map((user) => { const current = session?.id === user.id; const fullName = user.full_name?.trim(); return <article className="admin-user-card" key={user.id}><div className="admin-user-card__identity"><strong>{user.username} {current ? <span className="badge badge--muted">Sesión actual</span> : null}</strong>{fullName ? <span>{fullName}</span> : null}<span>{user.email || 'Sin correo'}{user.phone ? ` · ${user.phone}` : ''}</span>{user.seller_code ? <span className="admin-user-card__code">Código vendedor: {user.seller_code}</span> : null}</div><div className="admin-user-card__status"><span className={`badge ${user.is_active ? 'badge--ok' : 'badge--muted'}`}>{user.is_active ? 'Activo' : 'Inactivo'}</span></div><div className="admin-user-card__role"><strong>{user.role === 'support_admin' ? 'Superadministrador' : 'Vendedor'}</strong><small>{user.role === 'support_admin' ? 'Acceso total' : `${user.permissions.length} de ${permissionTotal} permisos`}</small></div><dl className="admin-user-card__dates"><div><dt>Último acceso</dt><dd>{formatDate(user.last_login_at)}</dd></div><div><dt>Creación</dt><dd>{formatDate(user.created_at)}</dd></div></dl><div className="admin-table-actions"><button className="table-action table-action--button" onClick={() => navigate(`/admin/usuarios/${user.id}/editar`)}><AdminIcon name="edit" />{user.is_active ? 'Editar' : 'Reactivar'}</button>{user.is_active && !current ? <button className="table-action table-action--button table-action--danger" onClick={(event) => { opener.current = event.currentTarget; setTarget(user) }}>Desactivar</button> : null}</div></article> })}</div> : null}
    </div>
    {target ? <div className="admin-user-modal"><section className="admin-user-modal__dialog" role="dialog" aria-modal="true" aria-labelledby="deactivate-title"><h2 id="deactivate-title">Desactivar cuenta</h2><p>No existe borrado físico: se conservarán los datos históricos, se cerrarán todas las sesiones y será necesaria una contraseña nueva para reactivar a {target.username}.</p>{mutationError ? <p className="ui-note ui-note--error" role="alert">{mutationError}</p> : null}<div className="admin-user-form__actions"><button ref={cancel} className="btn btn--secondary" onClick={close} disabled={submitting}>Cancelar</button><button className="btn btn--danger" onClick={() => void confirm()} disabled={submitting}>{submitting ? 'Desactivando…' : 'Desactivar cuenta'}</button></div></section></div> : null}
  </AdminLayout>
}
