import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { AdminLayout } from '../../components/admin/AdminLayout'
import { AdminPageHeader } from '../../components/admin/AdminPageHeader'
import { useAdminUser } from '../../components/admin/ProtectedRoute'
import { CustomerSearch } from '../../components/admin/CustomerSearch'
import { QuoteItemsEditor } from '../../components/admin/QuoteItemsEditor'
import { getSafeApiErrorMessage } from '../../services/api'
import { isSeller } from '../../services/authApi'
import { getCommercialQuote, issueCommercialQuote, saveCustomer } from '../../services/commercialQuotesApi'
import type { CommercialQuoteDetail, CustomerProfile, CustomerSnapshot, QuoteCurrency, QuoteEditorItem, SaleCondition } from '../../types/commercialQuote'
import { emptyQuoteItem, isEmptyItem, money, quoteTotals } from '../../utils/commercialQuote'

const emptyCustomer: CustomerSnapshot = { customer_profile_id: null, customer_business_name: '', customer_rut: '', customer_business_activity: '', customer_address: '', customer_phone: '', customer_city_or_commune: '', customer_contact_name: '', customer_email: '' }
const customerFields: Array<[keyof CustomerSnapshot, string, number, boolean, string]> = [['customer_business_name','Razón social',200,true,'business'],['customer_rut','RUT',12,true,'rut'],['customer_phone','Teléfono',30,true,'phone'],['customer_city_or_commune','Comuna o ciudad',120,true,'city'],['customer_business_activity','Giro',200,true,'activity'],['customer_address','Dirección',300,true,'address'],['customer_contact_name','Nombre de contacto',200,true,'contact'],['customer_email','Correo electrónico',254,false,'email']]
const fromDetail = (q: CommercialQuoteDetail): QuoteEditorItem[] => [...q.items].sort((a,b) => a.position-b.position).map<QuoteEditorItem>(i => ({ key: String(i.id), source: i.source, product_id: i.product_id ?? null, product_name: i.product_name, brand_name: i.brand_name ?? '', model_name: i.model_name ?? '', quantity: String(i.quantity), unit_net_amount: String(i.unit_net_amount), discount_percent: i.discount_percent ? String(i.discount_percent) : '' })).concat([emptyQuoteItem()])

export function CommercialQuoteEditorPage() {
  const currentUser = useAdminUser()
  const params = useParams(); const navigate = useNavigate(); const routeId = params.id ? Number(params.id) : undefined
  const id = routeId; const [customer, setCustomer] = useState(emptyCustomer); const [currency, setCurrency] = useState<QuoteCurrency>('CLP'); const [condition, setCondition] = useState<SaleCondition>('Cash'); const [description, setDescription] = useState(''); const [items, setItems] = useState<QuoteEditorItem[]>([emptyQuoteItem()]); const [persisted, setPersisted] = useState<CommercialQuoteDetail | null>(null)
  const [loading, setLoading] = useState(Boolean(routeId)); const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const firstError = useRef<HTMLDivElement>(null); const readonly = Boolean(routeId) || !isSeller(currentUser ?? undefined)
  const totals = useMemo(() => persisted && !dirty ? { net: persisted.net_amount, tax: persisted.tax_amount, total: persisted.total_amount } : quoteTotals(items.filter(i => !isEmptyItem(i)), currency), [currency, dirty, items, persisted])
  const apply = useCallback((quote: CommercialQuoteDetail) => { setPersisted(quote); setCustomer({ customer_profile_id: quote.customer_profile_id, customer_business_name: quote.customer_business_name, customer_rut: quote.customer_rut, customer_business_activity: quote.customer_business_activity, customer_address: quote.customer_address, customer_phone: quote.customer_phone, customer_city_or_commune: quote.customer_city_or_commune, customer_contact_name: quote.customer_contact_name, customer_email: quote.customer_email ?? '' }); setCurrency(quote.currency); setCondition(quote.sale_condition); setDescription(quote.detailed_description ?? ''); setItems(fromDetail(quote)); setDirty(false) }, [])
  useEffect(() => { if (!routeId) return; getCommercialQuote(routeId).then(apply).catch(e => setError(getSafeApiErrorMessage(e, 'No se pudo cargar la cotización.'))).finally(() => setLoading(false)) }, [apply, routeId])
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault() }; addEventListener('beforeunload', warn); return () => removeEventListener('beforeunload', warn) }, [dirty])
  const touch = () => { setDirty(true); setMessage('') }
  const selectCustomer = (p: CustomerProfile) => { setCustomer({ customer_profile_id:p.id, customer_business_name:p.business_name, customer_rut:p.rut, customer_business_activity:p.business_activity, customer_address:p.address, customer_phone:p.phone, customer_city_or_commune:p.city_or_commune, customer_contact_name:p.contact_name, customer_email:p.email ?? '' }); touch() }
  const validate = (requireItems: boolean) => { const errors: string[] = []; customerFields.filter(f=>f[3]).forEach(([key,label]) => { if (!String(customer[key]).trim()) errors.push(`${label} es obligatorio.`) }); if (!/^[0-9.]{7,10}-[0-9kK]$/.test(customer.customer_rut)) errors.push('Ingrese un RUT con formato válido.'); if (customer.customer_email && !/^\S+@\S+\.\S+$/.test(customer.customer_email)) errors.push('Ingrese un correo válido.'); if (!/\d/.test(customer.customer_phone)) errors.push('El teléfono debe contener al menos un dígito.'); const filled = items.filter(i=>!isEmptyItem(i)); for (const item of filled) { if (!item.product_name || !Number.isInteger(Number(item.quantity)) || Number(item.quantity)<1 || Number(item.unit_net_amount)<=0 || Number(item.discount_percent||0)<0 || Number(item.discount_percent||0)>100 || !/^\d*(\.\d{0,2})?$/.test(item.discount_percent)) errors.push('Corrija o elimine las filas de productos incompletas.') } if (requireItems && !filled.length) errors.push('Agregue al menos un ítem para emitir.'); setError(errors[0] ?? ''); if (errors.length) firstError.current?.focus(); return !errors.length }
  const payload = () => ({ ...customer, currency, sale_condition: condition, validity_days: 15, detailed_description: description || undefined, items: items.filter(i=>!isEmptyItem(i)).map(i => ({ source: i.source as 'Catalog'|'FreeText', ...(i.product_id ? { product_id:i.product_id } : {}), product_name:i.product_name, ...(i.brand_name ? {brand_name:i.brand_name}:{}), ...(i.model_name ? {model_name:i.model_name}:{}), quantity:Number(i.quantity), unit_net_amount:Number(i.unit_net_amount), ...(i.discount_percent ? {discount_percent:Number(i.discount_percent)}:{}) })) })
  const issue = async () => { if (saving || readonly || !validate(true) || !window.confirm('La cotización no podrá editarse después de emitirla. ¿Desea continuar?')) return; setSaving(true); setError(''); try { const issued = await issueCommercialQuote(payload()); apply(issued); setMessage(`Cotización emitida con folio ${issued.folio}.`); navigate(`/admin/cotizaciones/${issued.id}/editar`, { replace:true }) } catch(e) { setError(getSafeApiErrorMessage(e,'No se pudo emitir la cotización. Los datos del formulario se conservaron.')) } finally { setSaving(false) } }
  const goBack = () => { if (!dirty || window.confirm('Hay cambios sin guardar. ¿Desea volver?')) navigate('/admin/cotizaciones?vista=generadas') }
  if (loading) return <AdminLayout><p className="ui-note">Cargando cotización…</p></AdminLayout>
  return <AdminLayout><AdminPageHeader title={id ? 'Ver cotización' : 'Crear cotización'} actions={<div className="commercial-header-actions"><button type="button" className="btn btn--ghost" onClick={goBack}>Volver</button></div>} /><div ref={firstError} tabIndex={-1}>{error ? <p className="ui-note ui-note--error">{error}</p>:null}{message ? <p className="ui-note ui-note--success">{message}</p>:null}</div>
    <div className="commercial-editor-grid">
      <main className="commercial-editor-main">
      <section className="commercial-section commercial-customer-panel">
        <div className="commercial-customer-heading"><h2>Datos del cliente</h2><CustomerSearch disabled={Boolean(readonly)||saving} selectedId={customer.customer_profile_id} onSelect={selectCustomer} onUnlink={() => { setCustomer(c=>({...c,customer_profile_id:null})); touch() }} /></div>
        <div className="commercial-form-grid">{customerFields.map(([key,label,max,required,area])=><label key={key} style={{gridArea:area}}>{label}{required?' *':''}<input type={key==='customer_email'?'email':'text'} value={String(customer[key]??'')} maxLength={max} disabled={readonly||saving} onChange={e=>{setCustomer(c=>({...c,[key]:e.target.value}));touch()}} /></label>)}</div>
        <button className="btn btn--accent commercial-primary-action" type="button" disabled={readonly||saving} onClick={async()=>{if(!validate(false))return;setSaving(true);try{const body={business_name:customer.customer_business_name,rut:customer.customer_rut,business_activity:customer.customer_business_activity,address:customer.customer_address,phone:customer.customer_phone,city_or_commune:customer.customer_city_or_commune,contact_name:customer.customer_contact_name,email:customer.customer_email||null};const saved=await saveCustomer(body,customer.customer_profile_id??undefined);selectCustomer(saved);setMessage('Cliente guardado correctamente.')}catch(e){setError(getSafeApiErrorMessage(e,'No se pudo guardar el cliente. Si el RUT ya existe, búsquelo arriba.'))}finally{setSaving(false)}}}>Guardar cliente</button>
      </section>
        <section className="commercial-section">
          <h2>Datos comerciales y técnicos</h2>
          <div className="commercial-meta-grid">
            <label>Condición de venta<select value={condition} disabled={readonly||saving} onChange={e=>{setCondition(e.target.value as SaleCondition);touch()}}><option value="Cash">Contado</option><option value="Credit30Days">Crédito a 30 días</option></select></label>
            <label className="commercial-currency">Moneda<select value={currency} disabled={readonly||saving} onChange={e=>{const next=e.target.value as QuoteCurrency;if(items.some(i=>Number(i.unit_net_amount)>0)&&!window.confirm('No existe conversión monetaria. Se limpiarán los precios ingresados. ¿Continuar?'))return;setCurrency(next);setItems(current=>current.map(i=>({...i,unit_net_amount:'',discount_percent:''})));touch()}}><option>CLP</option><option>USD</option></select></label>
            <label>Folio<input readOnly value={persisted?.folio ?? 'Se asignará al emitir'} /></label>
            <label>Código vendedor<input readOnly value={persisted?.seller_code || 'Se informará al emitir'} /></label>
            <label>Fecha<input readOnly value={new Intl.DateTimeFormat('es-CL',{timeZone:'America/Santiago'}).format(new Date(persisted?.issued_on ?? persisted?.created_at ?? Date.now()))} /></label>
          </div>
          <h3>Ítems o productos</h3><QuoteItemsEditor currency={currency} items={items} disabled={Boolean(readonly)||saving} onChange={next=>{setItems(next);touch()}} />
        </section>
        <section className="commercial-section commercial-description"><h2>Descripción detallada opcional</h2><textarea rows={3} maxLength={1000} value={description} disabled={readonly||saving} onChange={e=>{setDescription(e.target.value);touch()}} /><small>{description.length}/1000</small></section>
        <div className="commercial-actions"><button className="btn btn--ghost" type="button" onClick={goBack}>Volver</button>{!readonly ? <button className="btn btn--accent commercial-primary-action" type="button" disabled={saving} onClick={()=>void issue()}>{saving ? 'Emitiendo…' : 'Emitir cotización'}</button> : null}<button className="btn btn--secondary" type="button" disabled title="Disponible cuando se implemente el servicio PDF">Descargar PDF</button><small>La descarga estará disponible después de implementar el servicio PDF.</small></div>
      </main>
      <aside className="commercial-values-column"><section className="commercial-section quote-values"><h2>Valores</h2><dl><div><dt>Neto</dt><dd>{money(totals.net,currency)}</dd></div><div><dt>IVA 19%</dt><dd>{money(totals.tax,currency)}</dd></div><div><dt>Total</dt><dd>{money(totals.total,currency)}</dd></div></dl><small>Vista previa; el cálculo definitivo lo realiza el servidor.</small></section></aside>
    </div>
  </AdminLayout>
}
